### ISSUE TITLE
Could not find a version that satisfies the requirement gps

### ISSUE THREAD

**Issue by frankforp** [dimgold/MeetNet#1]
Hello dimgold (Is this the name I should call you?)

I just run your code on my environment, and I think it is  a well-designed program for chatting among friends. I like it so much.

but I've got a problem that i can not install the gps module in python 2.7(I used pip install gps)
the error as follows
`  Could not find a version that satisfies the requirement gps (from versions: )
No matching distribution found for gps`

I don't know if you can help me on this problem.
Thank you very much!

Thanks,
Frank

**Comment by frankforp** [comment]
Sorry, I just went online  to find that  most Mac, Windows, and Linux desktop/laptop/server boxes don't have GPS hardware. And the OS's don't have a standard "location-services"-type API to access GPS (well, Mac does, but very few GPS drivers work with it; it's basically just useful for approximate geolocation, not real GPS)
https://stackoverflow.com/questions/30472142/gps-is-not-implemented-for-your-platform-kivy-plyer-pycharm

I am not sure how do you debug your code with GPS?

**Comment by dimgold** [comment]
Hi
I think that we tested the GPS feature only on android environment.
Try to disable the gps package and store some default location instead.

**Comment by frankforp** [comment]
Hi,

Thank you for your reply, I will try it.

Thanks,
Peng

**Comment by frankforp** [comment]
I closed this issue.
